const NAME_OR_PASSWORD_IS_NULL = "NAME_OR_PASSWORD_IS_NULL";
const USER_NAME_IS_REPETITION = "USER_NAME_IS_REPETITION";
const LOGIN_NAME_OR_PASSWORD_IS_FALSE = "LOGIN_NAME_OR_PASSWORD_IS_FALSE";
const THE_PASSWORD_IS_NOT_CORRECT = "THE_PASSWORD_IS_NOT_CORRECT";
const UN_AUTHORIZATION_USER = "UN_AUTHORIZATION_USER";
const USER_NOT_LOGIN_NOT_TOKEN = "USER_NOT_LOGIN_NOT_TOKEN"
const UN_AUTHORIZATION_LiCENSE = "UN_AUTHORIZATION_LiCENSE"
const LABEL_NO_EXISTS = "LABEL_NO_EXISTS"
module.exports = {
  NAME_OR_PASSWORD_IS_NULL,
  USER_NAME_IS_REPETITION,

  LOGIN_NAME_OR_PASSWORD_IS_FALSE,
  THE_PASSWORD_IS_NOT_CORRECT,
  UN_AUTHORIZATION_USER,
  USER_NOT_LOGIN_NOT_TOKEN,
  UN_AUTHORIZATION_LiCENSE,
  LABEL_NO_EXISTS
}